# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

# Set working directory
WORKDIR /app

# Copy package files and source code
COPY package.json bun.lock* ./
COPY src ./src
COPY tsconfig.json ./
COPY .env* ./
COPY README.md ./

# Install dependencies using Bun
RUN bun install

# Start the MCP server
CMD ["bun", "run", "src/index.ts"]
